export const CLIENT_NAMES_REQUEST = 'CLIENT_NAMES_REQUEST';
export const CLIENT_NAMES_RECEIVED = 'CLIENT_NAMES_RECEIVED';
export const CLIENT_NAMES_REQUEST_FAIL = 'CLIENT_NAMES_REQUEST_FAIL';
export const CLIENT_LISTS_REQUEST = 'CLIENT_LISTS_REQUEST';
export const CLIENT_LISTS_RECEIVED = 'CLIENT_LISTS_RECEIVED';
export const CLIENT_LISTS_REQUEST_FAIL = 'CLIENT_LISTS_REQUEST_FAIL';

