export const TURN_ON_UPLOAD_GUIDE = 'TURN_ON_UPLOAD_GUIDE';
export const TURN_OFF_UPLOAD_GUIDE = 'TURN_OFF_UPLOAD_GUIDE';
export const TURN_ON_GENERAL_GUIDE = 'TURN_ON_GENERAL_GUIDE';
export const TURN_OFF_GENERAL_GUIDE = 'TURN_OFF_GENERAL_GUIDE';
export const FORWARD_STEP = 'FORWARD_STEP';
export const BACKWARD_STEP = 'BACKWARD_STEP';
